name: Build FontLens APK

on:
  push:
    branches: [ main, master ]
  # pull_request:
    # branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle distribution (bin.zip)
        uses: actions/cache@v5
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-dist-8.7
          restore-keys: gradle-dist-8.7

      - name: Cache Gradle build cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-cache-

      - name: Download gradle-wrapper.jar
        run: |
          mkdir -p gradle/wrapper
          curl -Lo gradle/wrapper/gradle-wrapper.jar \
            https://github.com/gradle/gradle/raw/v8.7.0/gradle/wrapper/gradle-wrapper.jar

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        
      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > app/fontlens-release-key.jks
    
      - name: Create keystore properties
        run: |
          echo "storeFile=app/fontlens-release-key.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEYPASS }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEYPASS }}" >> keystore.properties
          
      # - name: Build debug APK
        # run: ./gradlew assembleDebug --stacktrace
      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
        
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: FontLens
          path: '**/*.apk'
          archive: false
          retention-days: 30